Tests_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: |
      cat package.json
      cat yarn.lock
    populate_script: make install
  bootstrap_script: yarn lerna bootstrap
  script: make
  matrix:
    - container:
        image: node:latest
      matrix:
        - name: "Tests@Node:Latest"
        - name: "CodeCoverage@Node:Latest"
          env:
            CODE_COVERAGE_RUN: true
            CODECOV_TOKEN: ENCRYPTED[230fd82953b0b0ed3fbde809dbad5bc8cf92a3b88e03d5b86c5124e01a890a12fde06130fb35af71c19ec4485d4519e3]
          code_coverage_artifacts:
            path: ./coverage/**
    - container:
        image: node:dubnium
      name: "Tests@Node:Dubnium"
    - container:
        image: node:erbium
      name: "Tests@Node:Erbium"
